services:
  postgres:
    image: postgres:16.4
    restart: no
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tennis
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro