version: '3.8'

services:
  db:
    image: cache.ecsc2024.it/library/mysql@sha256:566007208a3f1cc8f9df6b767665b5c9b800fc4fb5f863d17aa1df362880ed04
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
    volumes:
      - db_volume:/var/lib/mysql


  app:
    build: backend
    container_name: app
    restart: always
    environment:
      DBHOST: db
      LOCALTEST: "1"


  nginx:
    image: cache.ecsc2024.it/library/nginx@sha256:d2eb56950b84efe34f966a2b92efb1a1a2ea53e7e93b94cdf45a27cf3cd47fc0
    container_name: nginx
    restart: always
    ports:
      - "5000:80"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/usr/share/nginx/html

  bucket:
    image: cache.ecsc2024.it/library/nginx@sha256:d2eb56950b84efe34f966a2b92efb1a1a2ea53e7e93b94cdf45a27cf3cd47fc0
    ports:
      - "8080:80"
    volumes:
      - ./bucket/nginx.conf:/etc/nginx/nginx.conf
      - ./bucket/files:/var/www/html

volumes:
  db_volume: