services:
  hsm:
    build: ./hsm/dist
    volumes:
      - ./hsm/dist:/srv/hsm:ro
      - type: tmpfs
        target: /srv/hsm_data
    restart: unless-stopped
    # PORT EXPOSED FOR DEVELOPMENT ONLY
    ports:
      - '1337:1337'

  backend:
    build: ./webapp/
    restart: unless-stopped
    volumes:
      - ./webapp/src:/var/www/html/
    environment:
      HSM_HOST: hsm
      HSM_PORT: 1337
      DB_HOST: database
      DB_USER: root
      DB_PASS: "db_pass"
      SHARE_SECRET: "test_secret"
    ports:
      - '80:80'
  database:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: "db_pass"
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      # - ./db/data:/var/lib/mysql
    restart: unless-stopped
